name: CI
on:
    push:
        branches:
            - develop

jobs:
    tests:
        runs-on: ubuntu-latest
        steps:
            - name: Test
              run: |
                  echo "Running"
