name: Deploy to EC2 instance
on: push

jobs:
    continuous-integration:
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        steps:
            - name: Check out code
              uses: actions/checkout@v3

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Login in to Docker Hub -
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}
            - name: Build and push to Docker Hub
              uses: docker/build-push-action@v2
              with:
                  context: app
                  push: true
                  tags: tom54699/tobicord:latest
    continuous-deployment:
        runs-on: ubuntu-latest
        needs: [continuous-integration]
        if: github.ref == 'refs/heads/master'
        steps:
            - name: Configure AWS credentials -
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.aws_access_key_id }}
                  aws-secret-access-key: ${{ secrets.aws_secret_access_key }}
                  aws-region: us-west-2

            - name: Create CodeDeploy Deployment -
              id: deploy
              run: |
                  aws deploy create-deployment \
                  --application-name cicid-test \
                  --deployment-group-name cicid-test-groups \
                  --deployment-config-name CodeDeployDefault.OneAtATime \
                  --github-location repository=${{ github.repository }},commitId=${{ github.sha }}
